version: '3.8'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: airflow:12
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
      AIRFLOW__HOME: /opt/airflow
      AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT: 480
      AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT: 480
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags/builds/aws/a360/dags
      PYTHONPATH: /opt/airflow/dags/builds/aws
    ports:
      - "8080:8080"
    volumes: 
      - ./builds/aws:/opt/airflow/dags/builds/aws
    restart: always

volumes:
  postgres_data:
